### ISSUE TITLE
MacOS client patching

### ISSUE THREAD

**Issue by blandfx** [0blu/EverlookClassicLauncher#66]
Hello. 

I'm trying to get a 1.14.x client working on an arm mac (m1). Is there currently any way to obtain a patched client?

[https://wow-patching-service.blu.wtf](https://wow-patching-service.blu.wtf/ ) seems to be the url that was used for the "1.14.0.40618 (Apple Silicon)" cleint but no longer resolves. 

Thank you.

**Comment by 0blu** [comment]
Should be fixed now
