### ISSUE TITLE
mac os update to 15.0 Sequoia , Can't start client

### ISSUE THREAD

**Issue by 1024Cracker** [0blu/EverlookClassicLauncher#68]
<img width="597" alt="image" src="https://github.com/user-attachments/assets/87f23544-6725-437e-ae8f-cbf401a5e6dc">
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/c38679a1-00fc-4853-b72a-789a7a4bd376">

**Comment by 0blu** [comment]
It an error on Apple's side, it's fixed in `macOS Sequoia 15.2 beta`

**Comment by 1024Cracker** [comment]
> It an error on Apple's side, it's fixed in `macOS Sequoia 15.2 beta`

macOS Sequoia 15.1 already fixed now. thanks ^_^
